data_folder: "/ich/data"
raw_data_folder: "/ich/raw_data"
task: ich


dataset:
  train: /ich/data/fedmu
  val: /ich/data/fedmu/val.csv
  test: /ich/data/fedmu/test.csv
  forgotten: /ich/data/fedmu/forgotten.csv
  remembered: /ich/data/fedmu/remembered.csv
  resize:
    height: 224
    width: 224
  mean: [0.5, 0.5, 0.5]
  std: [0.5,0.5, 0.5]
  seed: 42

model:
  model_path: /ich/data/fedmu/checkpoints/origin/pretrain.pth
  torch_room: /home/user/fedmu/models
  pretrained: True
  drop_rate: 0
  mode: U-MultiClass
  num_classes: 2

eval:
  level: image
  metric: val/auc_avg
  
train:
  device: null
  gpu_exclude: [3]
  eval_interval: 500
  test_interval: 1000
  test_start: 10000
  use_CMSL: False
  checkpoint_dir: /ich/data/fedmu/checkpoints/
  resume_path: null
  batch_size: 64
  num_workers: 8
  max_epoch: null
  max_iter: 20000
  optimizer: 
    lr: 1.0e-5
    beta1: 0.9
    beta2: 0.9999
    weight_decay: 5.0e-4
  lr_scheduler:
    factor: 0.1
    patience: 2
    min_lr: 1.0e-7

test: 
  save_as_csv: True
  target_dir: /ich/data/fedmu/predicted

wandb:
  key: ""
  project: "fedmu_unlearn"
  run_name: "fcu"

fl:
  rounds: 20
  unlearn:
    low_freq: 0.5
    unlearn_iter: 100
    fusion_interval: 10
    optimizer: 
      lr: 1.0e-5
      beta1: 0.9
      beta2: 0.9999
      weight_decay: 5.0e-4
    lr_scheduler:
      factor: 0.1
      patience: 2
      min_lr: 1.0e-7
  test_start_round: 0
  eval_start_round: 0
  save_start_round: 40
  local_iter: 30
  wandb_global: False
  num_clients: 5

hooks:
  wandb: False
