data_folder: "isic skin lesion dataset" # target directory 
raw_data_folder: "isic skin lesion dataset" # directory of your original dataset
client_num: 5
dirichlet_alpha: 1.0
seed: 523

# cofig for memmership inference attack
backdoor:
  exclude_client: 2
